# Generated by Django 2.1.3 on 2018-11-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('readas', models.CharField(max_length=128)),
                ('meaning', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
